### ISSUE TITLE
Show history of search queries in pop-up

### ISSUE THREAD

**Issue by sojusnik** [brian-girko/multiple-highlight#11]
The "search document" field in the pop-up could have a dropdown menu, where the last X (f.i. 5) queries could be shown.
A checkbox to toggle this feature ("Save the search history in the dropdown menu") could be placed in the settings.

**Comment by brian-girko** [comment]
We are going to have it on the next release. Note that the extension only stores a query if navigation is requested (search next or previous, or press Enter key which is equal to search next).
