### ISSUE TITLE
Questions and Feature Requests

### ISSUE THREAD

**Issue by Bamajon1974** [brian-girko/multiple-highlight#2]
This extension is exactly what I am want for multiple simultaneous searches. 

Question: Does this extension accept Regular Expression inputs? 
Feature Request: Can options to customize the highlight text/background color of active and non-active search terms be implemented? 

Thanks in advance!

**Comment by brian-girko** [comment]
as of the next release use "r:your_reg_exp_here" to use RegExp matching.

> Can options to customize the highlight text/backgroun...

We are going to have this on the options page.

**Comment by Bamajon1974** [comment]
Awesome! Thank you very much for the quick replay and update! I will test
out and let you know if there are any bugs.

Thanks, Jon
