### ISSUE TITLE
Feature Request: Add option for underline and bold text (with highlight simultaneously)

### ISSUE THREAD

**Issue by easyteacher** [brian-girko/multiple-highlight#3]
Sometimes I want some keywords to be **underlined** and others to be **highlighted** at the same time. Currently I use Stylus to achieve that. I hope there is an option for underline and bold text.

![Snipaste_2020-03-03_23-34-26](https://user-images.githubusercontent.com/23738961/75791544-ae18bd80-5da7-11ea-9879-86124c0287e1.png)

**Comment by easyteacher** [comment]
It may be implemented like this:
**no prefix or h:** (highlight)
**u:** (underline)
**ru: or ur:** (underline, regex enabled)
**b:** (bold text)
**rb: or ub:** (bold text, regex enabled)

**Comment by brian-girko** [comment]
Thanks for the feature request. We will have it on 0.1.4

**Comment by easyteacher** [comment]
Thank you very much for your work!
