### ISSUE TITLE
Quick clearing of highlights

### ISSUE THREAD

**Issue by alexolog** [brian-girko/multiple-highlight#4]
Currently I use persistent highlights since clicking on the page closes the popup box.
That means that in order to clear the highlights I need to open the box, select the contents and delete them, which is uncomfortable on a laptop without a mouse.
ESC key management does not seem to work as intended on FF.

**Comment by lesca** [comment]
+1

My habit is use `CTRL-A` and type new keywords. This is a universal way to select thing. However `CTRL-A` doesn't work for this extension.

**Comment by brian-girko** [comment]
v

**Comment by brian-girko** [comment]
There is a new keyboard command to clear the highlights without the need to open the interface. Set a combination from the add-ons manager window of your browser.
