### ISSUE TITLE
Negative look-behind?

### ISSUE THREAD

**Issue by exec228** [brian-girko/multiple-highlight#5]
Hello!
Thanks for this add-on!
However, I have a question.
How can I highlight "tank" without "anti-tank"?
Does this add-on support r:(?<!-)tank ?

**Comment by brian-girko** [comment]
how about `r:[^-]tank`

**Comment by exec228** [comment]
That's cool roundabout for **one** symbol [set] :-)

**Comment by brian-girko** [comment]
I think you mean "Negative Lookbehind", right? It works for me
![1](https://user-images.githubusercontent.com/51436935/77526616-c77ec800-6e82-11ea-8b0e-50286a4bda0e.png)

Also backreferencing
![2](https://user-images.githubusercontent.com/51436935/77526693-e54c2d00-6e82-11ea-8bba-510da2cbf422.png)

**Comment by brian-girko** [comment]
just a reminder to make sure your word separator is space.

**Comment by exec228** [comment]
Sorry, you are correct, the word is "look-behind".
https://en.wikipedia.org/wiki/Ordnance_QF_17-pounder plenty of both keywords.
Formula I have inserted: 
r:(?<!-)tank
Screenshot
http://prntscr.com/rmftcw
No highlighting?

**Comment by brian-girko** [comment]
since the color is red it means your browser rejected the regex creation. Check the console for errors. It looks like this is not supported by your browser.

**Comment by exec228** [comment]
http://prntscr.com/rmg9z5
Hmm... Any chances you know how to fix it?

**Comment by brian-girko** [comment]
can you run the following code on the browser console:
```js
/(?<!-)tank/.test('anti-tank')
```

**Comment by exec228** [comment]
http://prntscr.com/rmrvp5

**Comment by brian-girko** [comment]
Seems like it is not yet supported by FF
https://stackoverflow.com/questions/49816707/firefox-invalid-regex-group

**Comment by exec228** [comment]
Sigh... Any other ways, external regex libs for Fx?

**Comment by brian-girko** [comment]
I dont think so. It is built into the Gecko engine.

**Comment by exec228** [comment]
Alas, must close the question because of a base constraint.
Thank you!
