### ISSUE TITLE
Feature Request: add options to save search 

### ISSUE THREAD

**Issue by lesca** [brian-girko/multiple-highlight#8]
Currently the only option is
> Save the query for the **current URL** and automatically perform the search when the popup is opened on the same URL

I'd suggest to add below options:
* Save the query for **all URLs**
  * Scenario: research something using the same keywords amongst multiple websites
* Save the query for the **current domain**
  * Scenario: research something using the same keywords on current website. However, user may do a different search on another website.

By adding these options, it also needs an option to let user to choose if they need to **automatically highlight** the keywords (without opening the extension and closing it again and again). It's better to use some shortcuts to switch the `highlight` or not option. 

This extension is awesome. I've replaced `CTRL-F` for this extension (i.e. use it as the default search for my browser). 

Thanks for your great work on this.

**Comment by sojusnik** [comment]
Totally agree on this two new options!

You could offer a dropdown menu where one could choose between 4 possibilities:

1. Don't save the query
2. Save the query for each URL
3. Save the query for each domain
4. Save the query for all URLs

If 2-4 are selected, then in another dropdown menu one could choose:

1. Highlight when pop-up is opened
2. Highlight when website is loaded (= highlight the keywords automatically, without opening the pop-up)

Those options would drastically improve your add-on and make it the most intuitive and functional keyword highlighter for Firefox!

**Comment by brian-girko** [comment]
I added a new option to adjust how the query is stored on the options page. Also, there is a new browser keyboard command to highlight without the need to open the interface (you need to set a custom keyboard shortcut for it).

**Comment by sojusnik** [comment]
That's a big step forward, thanks!

I wonder why the automatic highlighting (without opening the pop-up or using the keyboard shortcut) wasn't implemented too? Is this hard to achieve from a technical point of view?

**Comment by brian-girko** [comment]
To perform auto highlighting, the extension needs to have access to all the hostnames which is just too much. Currently, this extension only has access to the active tab when there is user interaction. Also, to be able to highlight things on document loads, the extension needs to observe web navigation. This feature just adds too many new permissions to the extension.

**Comment by sojusnik** [comment]
Too bad, clicking on the toolbar icon or using a keyboard shortcut on each page is actually counterintuitive to me when using a highlighter. And I'm not the only one, as seen [here](https://addons.mozilla.org/de/firefox/addon/multiple-highlight/reviews/1565700/).

Maybe a compromise would be a keyboard shortcut that highlights the keywords on every loaded page and not only the active one, although this would introduce a new permission?

BTW, why are you against adding new permissions? Your add-on is open source, so I don't see any privacy concerns here.

**Comment by sojusnik** [comment]
Another solution could be auto highlighting when switching to a tab, so that highlighting is done one tab at a time and therefore will save resources.

What do you think?

Your add-on is by far the best highlighter design wise and the only essential feature that is missing is auto highlighting.
